[theme]
primaryColor='#769488'
backgroundColor='#d0cbbf'
secondaryBackgroundColor='#c5c1b6'
textColor='#0c0c0c'
<<<<<<< HEAD
font='monospace'
=======
font='monospace'
>>>>>>> 968fc46d6774d618c18a1541f48b45247e92b083
